apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  root-password: cGFzc3dvcmQ0cm9vdA==  # Base64 kodowane "password4root"
  user: YmFzZXVzZXI=                 # Base64 kodowane "baseuser"
  user-password: cGFzc3dvcmQ0dXNlcg== # Base64 kodowane "password4user"
